version: '3.8'

services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: backend_test
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - ./db/schema.sql:/docker-entrypoint-initdb.d/1-schema.sql
      - ./db/seed.sql:/docker-entrypoint-initdb.d/2-seed.sql
      - db_data:/var/lib/mysql

  customers-api:
    build: ./customers-api
    ports:
      - "3001:3001"
    environment:
      - DB_HOST=db
      - DB_USER=user
      - DB_PASSWORD=password
      - DB_NAME=backend_test
      - DB_PORT=3306
      - PORT=3001
      - SERVICE_TOKEN=secret-service-token
    depends_on:
      - db

  orders-api:
    build: ./orders-api
    ports:
      - "3002:3002"
    environment:
      - DB_HOST=db
      - DB_USER=user
      - DB_PASSWORD=password
      - DB_NAME=backend_test
      - DB_PORT=3306
      - PORT=3002
      - SERVICE_TOKEN=secret-service-token
      - CUSTOMERS_API_BASE=http://customers-api:3001
    depends_on:
      - db
      - customers-api

volumes:
  db_data:
